create table
  if not exists public.pages (id text primary key);

create table
  if not exists public.prompts (
    id integer generated by default as identity primary key,
    page_id text not null references public.pages (id),
    user_id uuid not null default auth.uid () references auth.users (id),
    content text not null,
    response text,
    created_at timestamp without time zone not null default now ()
  );

create table
  if not exists public.votes (
    id integer generated by default as identity primary key,
    prompt_id integer not null references public.prompts (id),
    user_id uuid not null default auth.uid () references auth.users (id)
  );

create unique index unique_open_prompt_per_user_page on public.prompts (user_id, page_id)
where
  response is null;

alter table public.pages enable row level security;

alter table public.prompts enable row level security;

alter table public.votes enable row level security;

create policy pages_select_all on public.pages for
select
  using (true);

create policy prompts_select_all on public.prompts for
select
  using (true);

create policy votes_select_all on public.votes for
select
  using (true);

create
or replace function get_pages_with_vote_count () returns table (id text, vote_count bigint) as '
select
  p.id,
  count(v.id) as vote_count
from
  public.pages p
  left join public.prompts pr on p.id = pr.page_id
  left join public.votes v on pr.id = v.prompt_id
group by
  p.id;
' language sql;