
  create table "public"."pages" (
    "id" text not null
      );


alter table "public"."pages" enable row level security;


  create table "public"."prompts" (
    "id" integer generated by default as identity not null,
    "page_id" text not null,
    "user_id" uuid not null default auth.uid(),
    "content" text not null,
    "response" text,
    "created_at" timestamp without time zone not null default now()
      );


alter table "public"."prompts" enable row level security;


  create table "public"."votes" (
    "id" integer generated by default as identity not null,
    "prompt_id" integer not null,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."votes" enable row level security;

CREATE UNIQUE INDEX pages_pkey ON public.pages USING btree (id);

CREATE UNIQUE INDEX prompts_pkey ON public.prompts USING btree (id);

CREATE UNIQUE INDEX unique_open_prompt_per_user_page ON public.prompts USING btree (user_id, page_id) WHERE (response IS NULL);

CREATE UNIQUE INDEX votes_pkey ON public.votes USING btree (id);

alter table "public"."pages" add constraint "pages_pkey" PRIMARY KEY using index "pages_pkey";

alter table "public"."prompts" add constraint "prompts_pkey" PRIMARY KEY using index "prompts_pkey";

alter table "public"."votes" add constraint "votes_pkey" PRIMARY KEY using index "votes_pkey";

alter table "public"."prompts" add constraint "prompts_page_id_fkey" FOREIGN KEY (page_id) REFERENCES public.pages(id) not valid;

alter table "public"."prompts" validate constraint "prompts_page_id_fkey";

alter table "public"."prompts" add constraint "prompts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."prompts" validate constraint "prompts_user_id_fkey";

alter table "public"."votes" add constraint "votes_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES public.prompts(id) not valid;

alter table "public"."votes" validate constraint "votes_prompt_id_fkey";

alter table "public"."votes" add constraint "votes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."votes" validate constraint "votes_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_pages_with_vote_count()
 RETURNS TABLE(id text, vote_count bigint)
 LANGUAGE sql
AS $function$
select
  p.id,
  count(v.id) as vote_count
from
  public.pages p
  left join public.prompts pr on p.id = pr.page_id
  left join public.votes v on pr.id = v.prompt_id
group by
  p.id;
$function$
;

grant delete on table "public"."pages" to "anon";

grant insert on table "public"."pages" to "anon";

grant references on table "public"."pages" to "anon";

grant select on table "public"."pages" to "anon";

grant trigger on table "public"."pages" to "anon";

grant truncate on table "public"."pages" to "anon";

grant update on table "public"."pages" to "anon";

grant delete on table "public"."pages" to "authenticated";

grant insert on table "public"."pages" to "authenticated";

grant references on table "public"."pages" to "authenticated";

grant select on table "public"."pages" to "authenticated";

grant trigger on table "public"."pages" to "authenticated";

grant truncate on table "public"."pages" to "authenticated";

grant update on table "public"."pages" to "authenticated";

grant delete on table "public"."pages" to "service_role";

grant insert on table "public"."pages" to "service_role";

grant references on table "public"."pages" to "service_role";

grant select on table "public"."pages" to "service_role";

grant trigger on table "public"."pages" to "service_role";

grant truncate on table "public"."pages" to "service_role";

grant update on table "public"."pages" to "service_role";

grant delete on table "public"."prompts" to "anon";

grant insert on table "public"."prompts" to "anon";

grant references on table "public"."prompts" to "anon";

grant select on table "public"."prompts" to "anon";

grant trigger on table "public"."prompts" to "anon";

grant truncate on table "public"."prompts" to "anon";

grant update on table "public"."prompts" to "anon";

grant delete on table "public"."prompts" to "authenticated";

grant insert on table "public"."prompts" to "authenticated";

grant references on table "public"."prompts" to "authenticated";

grant select on table "public"."prompts" to "authenticated";

grant trigger on table "public"."prompts" to "authenticated";

grant truncate on table "public"."prompts" to "authenticated";

grant update on table "public"."prompts" to "authenticated";

grant delete on table "public"."prompts" to "service_role";

grant insert on table "public"."prompts" to "service_role";

grant references on table "public"."prompts" to "service_role";

grant select on table "public"."prompts" to "service_role";

grant trigger on table "public"."prompts" to "service_role";

grant truncate on table "public"."prompts" to "service_role";

grant update on table "public"."prompts" to "service_role";

grant delete on table "public"."votes" to "anon";

grant insert on table "public"."votes" to "anon";

grant references on table "public"."votes" to "anon";

grant select on table "public"."votes" to "anon";

grant trigger on table "public"."votes" to "anon";

grant truncate on table "public"."votes" to "anon";

grant update on table "public"."votes" to "anon";

grant delete on table "public"."votes" to "authenticated";

grant insert on table "public"."votes" to "authenticated";

grant references on table "public"."votes" to "authenticated";

grant select on table "public"."votes" to "authenticated";

grant trigger on table "public"."votes" to "authenticated";

grant truncate on table "public"."votes" to "authenticated";

grant update on table "public"."votes" to "authenticated";

grant delete on table "public"."votes" to "service_role";

grant insert on table "public"."votes" to "service_role";

grant references on table "public"."votes" to "service_role";

grant select on table "public"."votes" to "service_role";

grant trigger on table "public"."votes" to "service_role";

grant truncate on table "public"."votes" to "service_role";

grant update on table "public"."votes" to "service_role";


  create policy "pages_select_all"
  on "public"."pages"
  as permissive
  for select
  to public
using (true);



  create policy "prompts_select_all"
  on "public"."prompts"
  as permissive
  for select
  to public
using (true);



  create policy "votes_select_all"
  on "public"."votes"
  as permissive
  for select
  to public
using (true);



